import type { PaperKind, UpPreset } from "./types";

export type ProductCategory = string;

export interface ProductPreset {
  id: string;
  category: ProductCategory;
  name: string;
  quantity: number;
  width: number;
  height: number;
  sides: 1 | 2;
  colorSpec: string;
  stockKind: PaperKind;
  bindery: string[];
  impositionPreset: UpPreset;
  machine: string;
  notes: string;
}

export const PRODUCT_CATEGORIES: ProductCategory[] = [
  "Business Cards",
  "Flyers & Brochures",
  "Booklets & Books",
  "Signs & Banners",
  "Labels & Stickers",
  "Envelopes",
  "Invitations",
  "Copies",
  "Tea Party Cards",
  "Receipt Books",
  "Stamps",
  "Simcha Bags"
];

export const PRODUCT_PRESETS: ProductPreset[] = [
  {
    id: "bc-352-double",
    category: "Business Cards",
    name: "Business Cards 3.5 x 2 - 2 Sides",
    quantity: 1000,
    width: 3.5,
    height: 2,
    sides: 2,
    colorSpec: "4/4 full color",
    stockKind: "cover",
    bindery: ["Cut to size", "Box by set"],
    impositionPreset: "auto",
    machine: "Ricoh Pro C7200",
    notes: "Centered business card run on 13x19 cover."
  },
  {
    id: "bc-352-single",
    category: "Business Cards",
    name: "Business Cards 3.5 x 2 - 1 Side",
    quantity: 500,
    width: 3.5,
    height: 2,
    sides: 1,
    colorSpec: "4/0 full color",
    stockKind: "cover",
    bindery: ["Cut to size", "Box by set"],
    impositionPreset: "auto",
    machine: "Ricoh Pro C7200",
    notes: "Fast one-sided business card setup."
  },
  {
    id: "flyer-letter",
    category: "Flyers & Brochures",
    name: "Flyer 8.5 x 11 - 2 Sides",
    quantity: 500,
    width: 8.5,
    height: 11,
    sides: 2,
    colorSpec: "4/4 full color",
    stockKind: "text",
    bindery: ["Cut to size"],
    impositionPreset: "auto",
    machine: "Ricoh Pro C7200",
    notes: "Letter flyer or sell sheet."
  },
  {
    id: "brochure-trifold",
    category: "Flyers & Brochures",
    name: "Tri-fold Brochure 8.5 x 11",
    quantity: 1000,
    width: 8.5,
    height: 11,
    sides: 2,
    colorSpec: "4/4 full color",
    stockKind: "text",
    bindery: ["Cut to size", "Fold"],
    impositionPreset: "auto",
    machine: "Ricoh Pro C7200",
    notes: "Score or fold after printing."
  },
  {
    id: "booklet-letter",
    category: "Booklets & Books",
    name: "Booklet 8.5 x 11 Finished",
    quantity: 250,
    width: 8.5,
    height: 11,
    sides: 2,
    colorSpec: "4/4 booklet",
    stockKind: "text",
    bindery: ["Saddle stitch", "Fold"],
    impositionPreset: "auto",
    machine: "Ricoh Pro C7200",
    notes: "Booklet-only setup with cover rules."
  },
  {
    id: "booklet-half",
    category: "Booklets & Books",
    name: "Booklet 5.5 x 8.5 Finished",
    quantity: 300,
    width: 5.5,
    height: 8.5,
    sides: 2,
    colorSpec: "Black & white inside, color cover",
    stockKind: "text",
    bindery: ["Saddle stitch", "Fold"],
    impositionPreset: "auto",
    machine: "Ricoh Pro C7200",
    notes: "Small booklet with separate cover stock."
  },
  {
    id: "sign-18x24",
    category: "Signs & Banners",
    name: "Yard Sign 18 x 24",
    quantity: 25,
    width: 18,
    height: 24,
    sides: 1,
    colorSpec: "Full color wide format",
    stockKind: "wide-format",
    bindery: ["Cut to size"],
    impositionPreset: "auto",
    machine: "Large format printer",
    notes: "Wide-format sign workflow."
  },
  {
    id: "banner-24x72",
    category: "Signs & Banners",
    name: "Banner 24 x 72",
    quantity: 1,
    width: 24,
    height: 72,
    sides: 1,
    colorSpec: "Full color banner",
    stockKind: "wide-format",
    bindery: ["Hem", "Grommets"],
    impositionPreset: "auto",
    machine: "Large format printer",
    notes: "Roll media setup with finishing."
  },
  {
    id: "label-2x3",
    category: "Labels & Stickers",
    name: "Labels 2 x 3",
    quantity: 1000,
    width: 2,
    height: 3,
    sides: 1,
    colorSpec: "4/0 full color",
    stockKind: "specialty",
    bindery: ["Kiss cut"],
    impositionPreset: "auto",
    machine: "DC-618 cutter/creaser",
    notes: "Repeat labels across the sheet."
  },
  {
    id: "envelope-10",
    category: "Envelopes",
    name: "#10 Envelope",
    quantity: 500,
    width: 9.5,
    height: 4.125,
    sides: 1,
    colorSpec: "1/0 black",
    stockKind: "specialty",
    bindery: ["Pack by quantity"],
    impositionPreset: "auto",
    machine: "Ricoh Pro C7200",
    notes: "Envelope addressing or logo run."
  },
  {
    id: "envelope-9",
    category: "Envelopes",
    name: "#9 Reply Envelope",
    quantity: 500,
    width: 8.875,
    height: 3.875,
    sides: 1,
    colorSpec: "1/0 black",
    stockKind: "specialty",
    bindery: ["Pack by quantity"],
    impositionPreset: "auto",
    machine: "Ricoh Pro C7200",
    notes: "Reply envelope that nests inside a #10."
  },
  {
    id: "envelope-a2",
    category: "Envelopes",
    name: "A2 Announcement Envelope",
    quantity: 250,
    width: 5.75,
    height: 4.375,
    sides: 1,
    colorSpec: "1/0 black",
    stockKind: "specialty",
    bindery: ["Pack by quantity"],
    impositionPreset: "auto",
    machine: "Ricoh Pro C7200",
    notes: "Small announcement envelope for cards."
  },
  {
    id: "envelope-a7",
    category: "Envelopes",
    name: "A7 Invitation Envelope",
    quantity: 250,
    width: 7.25,
    height: 5.25,
    sides: 1,
    colorSpec: "4/0 full color",
    stockKind: "specialty",
    bindery: ["Pack by quantity"],
    impositionPreset: "auto",
    machine: "Ricoh Pro C7200",
    notes: "Invitation envelope sized for 5x7 inserts."
  },
  {
    id: "envelope-10-window",
    category: "Envelopes",
    name: "#10 Window Envelope",
    quantity: 500,
    width: 9.5,
    height: 4.125,
    sides: 1,
    colorSpec: "1/0 black",
    stockKind: "specialty",
    bindery: ["Pack by quantity", "Window envelope"],
    impositionPreset: "auto",
    machine: "Ricoh Pro C7200",
    notes: "Uses the #10 window envelope price table."
  },
  {
    id: "envelope-6x9-booklet",
    category: "Envelopes",
    name: "6 x 9 Booklet Envelope",
    quantity: 500,
    width: 6,
    height: 9,
    sides: 1,
    colorSpec: "1/0 black",
    stockKind: "specialty",
    bindery: ["Pack by quantity"],
    impositionPreset: "auto",
    machine: "Ricoh Pro C7200",
    notes: "Booklet envelope price table from the Gross price book."
  },
  {
    id: "envelope-6x9-open-end",
    category: "Envelopes",
    name: "6 x 9 Open End Envelope",
    quantity: 500,
    width: 6,
    height: 9,
    sides: 1,
    colorSpec: "1/0 black",
    stockKind: "specialty",
    bindery: ["Pack by quantity"],
    impositionPreset: "auto",
    machine: "Ricoh Pro C7200",
    notes: "Open-end envelope price table from the Gross price book."
  },
  {
    id: "envelope-remittance",
    category: "Envelopes",
    name: "6 3/4 Remittance Envelope",
    quantity: 500,
    width: 6.5,
    height: 3.625,
    sides: 1,
    colorSpec: "1/0 black",
    stockKind: "specialty",
    bindery: ["Pack by quantity"],
    impositionPreset: "auto",
    machine: "Ricoh Pro C7200",
    notes: "Only 500 and 1000 breaks are printed in the PDF."
  },
  {
    id: "envelope-9x12-booklet",
    category: "Envelopes",
    name: "9 x 12 Booklet Envelope",
    quantity: 500,
    width: 9,
    height: 12,
    sides: 1,
    colorSpec: "1/0 black",
    stockKind: "specialty",
    bindery: ["Pack by quantity"],
    impositionPreset: "auto",
    machine: "Ricoh Pro C7200",
    notes: "Large booklet envelope price table."
  },
  {
    id: "envelope-9x12-catalog",
    category: "Envelopes",
    name: "9 x 12 Catalog Envelope",
    quantity: 500,
    width: 9,
    height: 12,
    sides: 1,
    colorSpec: "1/0 black",
    stockKind: "specialty",
    bindery: ["Pack by quantity"],
    impositionPreset: "auto",
    machine: "Ricoh Pro C7200",
    notes: "Catalog envelope price table."
  },
  {
    id: "envelope-10x13-booklet",
    category: "Envelopes",
    name: "10 x 13 Booklet Envelope",
    quantity: 500,
    width: 10,
    height: 13,
    sides: 1,
    colorSpec: "1/0 black",
    stockKind: "specialty",
    bindery: ["Pack by quantity"],
    impositionPreset: "auto",
    machine: "Ricoh Pro C7200",
    notes: "10x13 booklet envelope price table."
  },
  {
    id: "envelope-10x13-catalog",
    category: "Envelopes",
    name: "10 x 13 Catalog Envelope",
    quantity: 500,
    width: 10,
    height: 13,
    sides: 1,
    colorSpec: "1/0 black",
    stockKind: "specialty",
    bindery: ["Pack by quantity"],
    impositionPreset: "auto",
    machine: "Ricoh Pro C7200",
    notes: "10x13 catalog envelope price table."
  },
  {
    id: "envelope-a8",
    category: "Envelopes",
    name: "A8 Envelope",
    quantity: 500,
    width: 8.125,
    height: 5.5,
    sides: 1,
    colorSpec: "1/0 black",
    stockKind: "specialty",
    bindery: ["Pack by quantity"],
    impositionPreset: "auto",
    machine: "Ricoh Pro C7200",
    notes: "A8 envelope price table."
  },
  {
    id: "envelope-a9-pricebook",
    category: "Envelopes",
    name: "A9 Envelope",
    quantity: 500,
    width: 8.75,
    height: 5.75,
    sides: 1,
    colorSpec: "1/0 black",
    stockKind: "specialty",
    bindery: ["Pack by quantity"],
    impositionPreset: "auto",
    machine: "Ricoh Pro C7200",
    notes: "A9 envelope price table."
  },
  {
    id: "label-sheet-8511",
    category: "Labels & Stickers",
    name: "8.5 x 11 Label Sheet",
    quantity: 300,
    width: 8.5,
    height: 11,
    sides: 1,
    colorSpec: "4/0 full color",
    stockKind: "specialty",
    bindery: ["Sheet labels"],
    impositionPreset: "auto",
    machine: "Ricoh Pro C7200",
    notes: "White, glossy, gold, silver, or clear label material."
  },
  {
    id: "label-sheet-1117",
    category: "Labels & Stickers",
    name: "11 x 17 Label Sheet",
    quantity: 300,
    width: 11,
    height: 17,
    sides: 1,
    colorSpec: "4/0 full color",
    stockKind: "specialty",
    bindery: ["Sheet labels"],
    impositionPreset: "auto",
    machine: "Ricoh Pro C7200",
    notes: "11x17 label pricing from the PDF."
  },
  {
    id: "label-sheet-1218",
    category: "Labels & Stickers",
    name: "12 x 18 Label Sheet",
    quantity: 300,
    width: 12,
    height: 18,
    sides: 1,
    colorSpec: "4/0 full color",
    stockKind: "specialty",
    bindery: ["Sheet labels", "Die cut"],
    impositionPreset: "auto",
    machine: "DC-618 cutter/creaser",
    notes: "12x18 label pricing and die-cut option."
  },
  {
    id: "invite-5x7",
    category: "Invitations",
    name: "Invitation 5 x 7",
    quantity: 250,
    width: 5,
    height: 7,
    sides: 2,
    colorSpec: "4/4 full color",
    stockKind: "cover",
    bindery: ["Cut to size", "Score", "Round corners"],
    impositionPreset: "auto",
    machine: "Ricoh Pro C7200",
    notes: "Cover stock invitation or postcard."
  },
  {
    id: "invite-a8",
    category: "Invitations",
    name: "A8 Invitation 10.5 x 7.5",
    quantity: 500,
    width: 10.5,
    height: 7.5,
    sides: 2,
    colorSpec: "4/4 full color",
    stockKind: "cover",
    bindery: ["Cut to size", "Score"],
    impositionPreset: "auto",
    machine: "Ricoh Pro C7200",
    notes: "PDF price book A8 invitation."
  },
  {
    id: "invite-a9-thin",
    category: "Invitations",
    name: "A9 Thin Invitation 11 x 8.5",
    quantity: 500,
    width: 11,
    height: 8.5,
    sides: 2,
    colorSpec: "4/4 full color",
    stockKind: "cover",
    bindery: ["Cut to size", "Score"],
    impositionPreset: "auto",
    machine: "Ricoh Pro C7200",
    notes: "PDF price book A9 thin invitation."
  },
  {
    id: "invite-a9-thick",
    category: "Invitations",
    name: "A9 Thick Invitation 11 x 8.5",
    quantity: 500,
    width: 11,
    height: 8.5,
    sides: 2,
    colorSpec: "4/4 full color",
    stockKind: "cover",
    bindery: ["Cut to size", "Score"],
    impositionPreset: "auto",
    machine: "Ricoh Pro C7200",
    notes: "PDF price book A9 thick invitation."
  },
  {
    id: "invite-a10-white",
    category: "Invitations",
    name: "A10 Invitation White 11.5 x 9",
    quantity: 500,
    width: 11.5,
    height: 9,
    sides: 2,
    colorSpec: "4/4 full color",
    stockKind: "cover",
    bindery: ["Cut to size", "Score"],
    impositionPreset: "auto",
    machine: "Ricoh Pro C7200",
    notes: "PDF price book A10 white invitation."
  },
  {
    id: "invite-a10-antique",
    category: "Invitations",
    name: "A10 Invitation Antique White 11.5 x 9",
    quantity: 500,
    width: 11.5,
    height: 9,
    sides: 2,
    colorSpec: "4/4 full color",
    stockKind: "cover",
    bindery: ["Cut to size", "Score"],
    impositionPreset: "auto",
    machine: "Ricoh Pro C7200",
    notes: "PDF price book A10 antique white invitation."
  },
  {
    id: "invite-small-postcard",
    category: "Invitations",
    name: "Small Postcard 4.25 x 6",
    quantity: 500,
    width: 4.25,
    height: 6,
    sides: 2,
    colorSpec: "4/4 full color",
    stockKind: "cover",
    bindery: ["Cut to size"],
    impositionPreset: "auto",
    machine: "Ricoh Pro C7200",
    notes: "PDF price book small postcard."
  },
  {
    id: "invite-large-postcard",
    category: "Invitations",
    name: "Large Postcard 5.5 x 8.5",
    quantity: 500,
    width: 5.5,
    height: 8.5,
    sides: 2,
    colorSpec: "4/4 full color",
    stockKind: "cover",
    bindery: ["Cut to size"],
    impositionPreset: "auto",
    machine: "Ricoh Pro C7200",
    notes: "PDF price book large postcard."
  },
  {
    id: "tea-party-card",
    category: "Tea Party Cards",
    name: "Tea Party Cards",
    quantity: 400,
    width: 5.5,
    height: 8.5,
    sides: 2,
    colorSpec: "4/4 full color",
    stockKind: "cover",
    bindery: ["Cut to size"],
    impositionPreset: "auto",
    machine: "Ricoh Pro C7200",
    notes: "PDF page 5 tea party cards."
  },
  {
    id: "receipt-book-40",
    category: "Receipt Books",
    name: "40 Receipt Books - 2 Part",
    quantity: 3,
    width: 8.5,
    height: 5.5,
    sides: 1,
    colorSpec: "1/0 black",
    stockKind: "text",
    bindery: ["Numbering", "Padding"],
    impositionPreset: "auto",
    machine: "Folder/stapler/finishing",
    notes: "40 receipts per book with numbers."
  },
  {
    id: "receipt-book-50",
    category: "Receipt Books",
    name: "50 Receipt Books - 2 Part",
    quantity: 3,
    width: 8.5,
    height: 5.5,
    sides: 1,
    colorSpec: "1/0 black",
    stockKind: "text",
    bindery: ["Numbering", "Padding"],
    impositionPreset: "auto",
    machine: "Folder/stapler/finishing",
    notes: "50 receipts per book with numbers."
  },
  {
    id: "stamp-self-ink",
    category: "Stamps",
    name: "Self Ink Stamp",
    quantity: 1,
    width: 2,
    height: 1,
    sides: 1,
    colorSpec: "Black / Red",
    stockKind: "specialty",
    bindery: ["Proof"],
    impositionPreset: "auto",
    machine: "Outsource",
    notes: "Styles 1438, 1850, 2260, 2770, 3458, 4040, 4090."
  },
  {
    id: "simcha-bag-paper",
    category: "Simcha Bags",
    name: "Paper Simcha Bags 4.3 x 8",
    quantity: 100,
    width: 4.3,
    height: 8,
    sides: 1,
    colorSpec: "4/0 full color",
    stockKind: "specialty",
    bindery: ["Pack by quantity"],
    impositionPreset: "auto",
    machine: "Ricoh Pro C7200",
    notes: "Paper simcha bag price table."
  },
  {
    id: "simcha-bag-plastic",
    category: "Simcha Bags",
    name: "Plastic Simcha Bags 5.15 x 8.4",
    quantity: 100,
    width: 5.15,
    height: 8.4,
    sides: 1,
    colorSpec: "4/0 full color",
    stockKind: "specialty",
    bindery: ["Pack by quantity"],
    impositionPreset: "auto",
    machine: "Ricoh Pro C7200",
    notes: "Plastic simcha bag price table."
  },
  {
    id: "copies-letter",
    category: "Copies",
    name: "Copies 8.5 x 11",
    quantity: 100,
    width: 8.5,
    height: 11,
    sides: 1,
    colorSpec: "1/0 black",
    stockKind: "text",
    bindery: ["Collate", "Staple"],
    impositionPreset: "auto",
    machine: "Ricoh Pro C7200",
    notes: "Copy job with simple finishing."
  }
];

export const CATEGORY_FINISHING: Record<string, string[]> = {
  "Business Cards": ["Cut to size", "Round corners", "Box by set", "Shrink wrap", "Die cut"],
  "Flyers & Brochures": ["Cut to size", "Score", "Perforation", "Fold", "Tri fold", "Z fold", "Half fold", "Parallel fold", "Gate fold", "Shrink wrap"],
  "Booklets & Books": ["Fold", "Saddle stitch", "Perfect bind", "Spiral bind", "Trim booklets"],
  "Signs & Banners": ["Cut to size", "Hem", "Grommets", "Mount to foamboard"],
  "Labels & Stickers": ["Kiss cut", "Die cut", "Cut to size", "Roll labels", "Sheet labels", "Laminate"],
  Envelopes: ["Pack by quantity", "Window envelope", "Addressing"],
  Invitations: ["Cut to size", "Score", "Perforation", "Fold", "Round corners", "Envelope match", "Numbering"],
  Copies: ["Collate", "Staple", "Hole punch", "Drilling", "Fold", "Padding"],
  "Tea Party Cards": ["Cut to size", "Box by set"],
  "Receipt Books": ["Numbering", "Red numbering", "Padding", "Perforation", "Drilling"],
  Stamps: ["Proof", "Outsource"],
  "Simcha Bags": ["Pack by quantity"]
};
