-- Gross Printing MIS v0.4.4 - Owner Admin, Back Office, recovery, and permanent private files
-- Run this entire file in Supabase Dashboard > SQL Editor.
-- Safe to run again. The permanent owner email is jobs@grossprinting.com.

create table if not exists public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text,
  display_name text,
  role text not null default 'front_desk'
    check (role in ('admin', 'front_desk', 'prepress', 'press', 'finishing')),
  is_active boolean not null default false,
  is_owner boolean not null default false,
  title text,
  department text,
  last_activity_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles add column if not exists is_owner boolean not null default false;
alter table public.profiles add column if not exists title text;
alter table public.profiles add column if not exists department text;
alter table public.profiles add column if not exists last_activity_at timestamptz;

create table if not exists public.app_data (
  id text primary key,
  data jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id) on delete set null
);

create table if not exists public.app_sessions (
  id uuid primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  email text,
  started_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  signed_out_at timestamptz,
  revoked_at timestamptz,
  current_view text,
  user_agent text,
  device_label text,
  browser_label text,
  ip_address text
);

create index if not exists app_sessions_user_id_idx on public.app_sessions(user_id);
create index if not exists app_sessions_last_seen_idx on public.app_sessions(last_seen_at desc);

create table if not exists public.activity_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  actor_email text,
  action text not null,
  category text not null default 'account',
  target_user_id uuid references auth.users(id) on delete set null,
  target_email text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists activity_logs_created_at_idx on public.activity_logs(created_at desc);
create index if not exists activity_logs_user_id_idx on public.activity_logs(user_id);

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_touch_updated_at on public.profiles;
create trigger profiles_touch_updated_at
before update on public.profiles
for each row execute function public.touch_updated_at();

drop trigger if exists app_data_touch_updated_at on public.app_data;
create trigger app_data_touch_updated_at
before update on public.app_data
for each row execute function public.touch_updated_at();

create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  owner_email constant text := 'jobs@grossprinting.com';
  owner_account boolean := lower(coalesce(new.email, '')) = lower(owner_email);
begin
  insert into public.profiles (user_id, email, display_name, role, is_active, is_owner, title, department)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'display_name', new.raw_user_meta_data ->> 'full_name', new.raw_user_meta_data ->> 'name', split_part(coalesce(new.email, ''), '@', 1)),
    case when owner_account then 'admin' else 'front_desk' end,
    owner_account,
    owner_account,
    case when owner_account then 'Owner Administrator' else null end,
    case when owner_account then 'Administration' else null end
  )
  on conflict (user_id) do update
  set email = excluded.email,
      display_name = coalesce(nullif(public.profiles.display_name, ''), excluded.display_name),
      role = case when owner_account then 'admin' else public.profiles.role end,
      is_active = case when owner_account then true else public.profiles.is_active end,
      is_owner = case when owner_account then true else public.profiles.is_owner end,
      title = case when owner_account then 'Owner Administrator' else public.profiles.title end,
      department = case when owner_account then 'Administration' else public.profiles.department end;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert or update of email, raw_user_meta_data on auth.users
for each row execute function public.handle_new_auth_user();

insert into public.profiles (user_id, email, display_name, role, is_active, is_owner, title, department)
select
  users.id,
  users.email,
  coalesce(users.raw_user_meta_data ->> 'display_name', users.raw_user_meta_data ->> 'full_name', users.raw_user_meta_data ->> 'name', split_part(coalesce(users.email, ''), '@', 1)),
  case when lower(coalesce(users.email, '')) = lower('jobs@grossprinting.com') then 'admin' else 'front_desk' end,
  lower(coalesce(users.email, '')) = lower('jobs@grossprinting.com'),
  lower(coalesce(users.email, '')) = lower('jobs@grossprinting.com'),
  case when lower(coalesce(users.email, '')) = lower('jobs@grossprinting.com') then 'Owner Administrator' else null end,
  case when lower(coalesce(users.email, '')) = lower('jobs@grossprinting.com') then 'Administration' else null end
from auth.users as users
on conflict (user_id) do update
set email = excluded.email,
    display_name = coalesce(nullif(public.profiles.display_name, ''), excluded.display_name),
    role = case when excluded.is_owner then 'admin' else public.profiles.role end,
    is_active = case when excluded.is_owner then true else public.profiles.is_active end,
    is_owner = case when excluded.is_owner then true else public.profiles.is_owner end,
    title = case when excluded.is_owner then 'Owner Administrator' else public.profiles.title end,
    department = case when excluded.is_owner then 'Administration' else public.profiles.department end;

create or replace function public.protect_owner_profile()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if old.is_owner then
    new.is_owner := true;
    new.role := 'admin';
    new.is_active := true;
    new.title := coalesce(nullif(new.title, ''), 'Owner Administrator');
    new.department := coalesce(nullif(new.department, ''), 'Administration');
  end if;
  return new;
end;
$$;

drop trigger if exists profiles_protect_owner on public.profiles;
create trigger profiles_protect_owner
before update on public.profiles
for each row execute function public.protect_owner_profile();

create or replace function public.current_app_role()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select role
  from public.profiles
  where user_id = (select auth.uid())
    and is_active = true
  limit 1;
$$;

create or replace function public.is_active_app_user()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where user_id = (select auth.uid())
      and is_active = true
  );
$$;

revoke all on function public.current_app_role() from public;
revoke all on function public.is_active_app_user() from public;
grant execute on function public.current_app_role() to authenticated;
grant execute on function public.is_active_app_user() to authenticated;

alter table public.profiles enable row level security;
alter table public.app_data enable row level security;
alter table public.app_sessions enable row level security;
alter table public.activity_logs enable row level security;

drop policy if exists "Users can read their profile" on public.profiles;
create policy "Users can read their profile"
on public.profiles for select to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "Admins can read all profiles" on public.profiles;
create policy "Admins can read all profiles"
on public.profiles for select to authenticated
using ((select public.current_app_role()) = 'admin');

drop policy if exists "Admins can update profiles" on public.profiles;
create policy "Admins can update profiles"
on public.profiles for update to authenticated
using ((select public.current_app_role()) = 'admin')
with check ((select public.current_app_role()) = 'admin');

drop policy if exists "Active users can read MIS data" on public.app_data;
create policy "Active users can read MIS data"
on public.app_data for select to authenticated
using ((select public.is_active_app_user()));

drop policy if exists "Active users can create MIS data" on public.app_data;
create policy "Active users can create MIS data"
on public.app_data for insert to authenticated
with check ((select public.is_active_app_user()));

drop policy if exists "Active users can update MIS data" on public.app_data;
create policy "Active users can update MIS data"
on public.app_data for update to authenticated
using ((select public.is_active_app_user()))
with check ((select public.is_active_app_user()));

drop policy if exists "Users can read own sessions" on public.app_sessions;
create policy "Users can read own sessions"
on public.app_sessions for select to authenticated
using ((select auth.uid()) = user_id or (select public.current_app_role()) = 'admin');

drop policy if exists "Admins can read activity" on public.activity_logs;
create policy "Admins can read activity"
on public.activity_logs for select to authenticated
using ((select public.current_app_role()) = 'admin');

grant select on public.profiles to authenticated;
grant update (display_name, role, is_active, title, department, last_activity_at, updated_at) on public.profiles to authenticated;
grant select, insert, update on public.app_data to authenticated;
grant select on public.app_sessions to authenticated;
grant select on public.activity_logs to authenticated;

insert into public.app_data (id, data)
values ('gross-printing-demo-state-v1', '{}'::jsonb)
on conflict (id) do nothing;

-- If your permanent owner uses another email, change jobs@grossprinting.com in this file
-- before running it, or run the following once after that Auth account exists:
-- update public.profiles
-- set role = 'admin', is_active = true, is_owner = true,
--     title = 'Owner Administrator', department = 'Administration'
-- where lower(email) = lower('YOUR-OWNER-EMAIL@example.com');

-- v0.4.4 permanent private paperwork and artwork storage
insert into storage.buckets (id, name, public, file_size_limit)
values ('mis-files', 'mis-files', false, 104857600)
on conflict (id) do update
set public = false,
    file_size_limit = excluded.file_size_limit;

drop policy if exists "Active staff can read MIS files" on storage.objects;
create policy "Active staff can read MIS files"
on storage.objects for select to authenticated
using (
  bucket_id = 'mis-files'
  and (select public.is_active_app_user())
);

drop policy if exists "Admins can upload MIS files" on storage.objects;
create policy "Admins can upload MIS files"
on storage.objects for insert to authenticated
with check (
  bucket_id = 'mis-files'
  and (select public.current_app_role()) = 'admin'
);

drop policy if exists "Admins can update MIS files" on storage.objects;
create policy "Admins can update MIS files"
on storage.objects for update to authenticated
using (
  bucket_id = 'mis-files'
  and (select public.current_app_role()) = 'admin'
)
with check (
  bucket_id = 'mis-files'
  and (select public.current_app_role()) = 'admin'
);

drop policy if exists "Admins can delete MIS files" on storage.objects;
create policy "Admins can delete MIS files"
on storage.objects for delete to authenticated
using (
  bucket_id = 'mis-files'
  and (select public.current_app_role()) = 'admin'
);
