-- Gross Printing MIS v0.6.7.1
-- Secure public website quote intake.
-- ADDITIVE / NON-DESTRUCTIVE: does not delete, truncate, replace, or reset MIS production data.
-- Run AFTER GROSS_PRINTING_MIS_V067_SERVER_SECURITY.sql.

begin;

create table if not exists public.public_quote_requests (
  id uuid primary key default gen_random_uuid(),
  request_number bigint generated by default as identity unique,
  status text not null default 'new' check (status in ('new','emailed','reviewing','quoted','closed','spam')),
  source text not null default 'public-website',
  submitted_at timestamptz not null default now(),
  name text not null,
  email text not null,
  phone text,
  company text,
  product text not null,
  quantity integer not null check (quantity > 0 and quantity <= 1000000),
  size text,
  sides smallint not null check (sides in (1,2)),
  paper text not null,
  finishing text,
  turnaround text not null,
  notes text,
  estimated_total numeric(12,2) not null check (estimated_total >= 0),
  estimated_per_unit numeric(12,3) not null check (estimated_per_unit >= 0),
  estimate_confidence text not null,
  estimate_breakdown jsonb not null default '[]'::jsonb,
  estimate_note text,
  staff_email_sent_at timestamptz,
  customer_email_sent_at timestamptz,
  email_error text,
  updated_at timestamptz not null default now()
);

create index if not exists public_quote_requests_status_submitted_idx
  on public.public_quote_requests(status, submitted_at desc);
create index if not exists public_quote_requests_email_submitted_idx
  on public.public_quote_requests(lower(email), submitted_at desc);

alter table public.public_quote_requests enable row level security;
revoke all on public.public_quote_requests from anon, authenticated;
grant select, insert, update on public.public_quote_requests to service_role;
grant usage, select on sequence public.public_quote_requests_request_number_seq to service_role;

create table if not exists public.public_request_rate_limits (
  key_hash text primary key,
  window_start timestamptz not null default now(),
  request_count integer not null default 0,
  updated_at timestamptz not null default now()
);

alter table public.public_request_rate_limits enable row level security;
revoke all on public.public_request_rate_limits from anon, authenticated;
grant select, insert, update, delete on public.public_request_rate_limits to service_role;

create or replace function public.check_public_quote_rate_limit(
  p_key text,
  p_window_seconds integer,
  p_limit integer
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  now_value timestamptz := clock_timestamp();
  count_value integer;
  start_value timestamptz;
begin
  if p_key is null or length(p_key) < 16 or p_window_seconds < 1 or p_limit < 1 then
    return false;
  end if;

  insert into public.public_request_rate_limits(key_hash, window_start, request_count, updated_at)
  values (p_key, now_value, 1, now_value)
  on conflict (key_hash) do update
  set
    window_start = case
      when public.public_request_rate_limits.window_start <= now_value - make_interval(secs => p_window_seconds)
        then now_value
      else public.public_request_rate_limits.window_start
    end,
    request_count = case
      when public.public_request_rate_limits.window_start <= now_value - make_interval(secs => p_window_seconds)
        then 1
      else public.public_request_rate_limits.request_count + 1
    end,
    updated_at = now_value
  returning request_count, window_start into count_value, start_value;

  return count_value <= p_limit;
end;
$$;

revoke all on function public.check_public_quote_rate_limit(text, integer, integer) from public, anon, authenticated;
grant execute on function public.check_public_quote_rate_limit(text, integer, integer) to service_role;

-- Keep the rate-limit table small. This is safe housekeeping for this NEW v0.6.7.1-only table.
delete from public.public_request_rate_limits
where updated_at < now() - interval '7 days';

commit;

-- Verification (read-only):
-- select count(*) from public.public_quote_requests;
-- select status, count(*) from public.public_quote_requests group by status order by status;
